import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import { MDXProvider } from '@mdx-js/react/lib';
import Layout from '@/components/Layout';
import Head from 'next/head';


//const articleNameArr:string[] = ['first.mdx','second.mdx','third.mdx'];


//pages/posts에 mdx파일들을 동적으로 articleNameArr 추가
const articleNameArr:string[] = 
  preval `module.exports = require('fs').readdirSync("./pages/posts")` || [];

//문장 내용
const articles:article[] = articleNameArr.map(
  (name:string)=>{
    const{
      meta:{title,author,tag,description,createTime}
    } = require("./posts/" + name);
    return{title,author,tag,description,createTime,path:name.split('.')[0]};  
  }
).sort((a,b)=>Date.parse(a.createTime) - Date.parse(b.createTime));



export default function App({ Component, pageProps,router }: AppProps) {
  return (
    <>
      <Head>
        <title>NextBlog</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout articles={articles}>
        <Component  router={router} articles={articles} {...pageProps} />
      </Layout>
    </>
  );
}
